### ISSUE TITLE
Sub display

### ISSUE THREAD

**Issue by baronTommy** [binaryage/totalspaces2-api#8]
```ruby
display_id = TotalSpaces2.main_display[:display_id]
TotalSpaces2.move_to_space_on_Display(1, display_id)
```

Can you target sub display?
TotalSpaces2.sub_display[:display_id]

**Comment by sdsykes** [comment]
What is a sub display? Do you mean any display that's not the main one?

You can get all the displays using the display_list method.

**Comment by baronTommy** [comment]
Sorry for lack of information

What is a sub display? Do you mean any display that's not the main one?
↑
yes sub display

Active window of sub display
I want to move other spaces


![sub display](https://www.dropbox.com/s/dv7y41rro557cxz/LeftMouseWindow_%E3%81%A8_EV2450%EF%BC%882%EF%BC%89.png?dl=1 "")

**Comment by baronTommy** [comment]
```ruby
puts "TotalSpaces API version: #{TotalSpaces2.api_version}"
```
```bash
TotalSpaces API version: 2.2.1
```

```ruby
puts TotalSpaces2.display_list
```

```bash
{:display_id=>1892243968, :display_name=>"EV2450", :width=>1920, :height=>1080}
{:display_id=>1892243970, :display_name=>"EV2450", :width=>1080, :height=>1920}
```bash

**Comment by baronTommy** [comment]
![setting](https://www.dropbox.com/s/3cardpjjud0esj0/LeftMouseWindow_%E3%81%A8_Mission_Control.png?dl=1)

**Comment by sdsykes** [comment]
Is this what you mean?

    irb(main):001:0> require 'totalspaces2'
    => true
    irb(main):002:0> TotalSpaces2.display_list
    => [{:display_id=>69679040, :display_name=>"Color LCD", :width=>1440, :height=>900}, {:display_id=>69514913, :display_name=>"LED Cinema Display", :width=>2560, :height=>1440}]
irb(main):003:0> TotalSpaces2.move_to_space_on_display(2, 69514913)
    => true
    irb(main):004:0>

(Moves to space 2 on my LED Cinema Display)

**Comment by baronTommy** [comment]
solved
![giphy](https://cloud.githubusercontent.com/assets/16768208/23900888/43e1e262-08fe-11e7-8029-d2958f80606c.gif)
